language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "beatenpath";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: beaten-path
  api_key:
    secure: N/vQnFMEx53yyo4y+DVwswFk8hJPGYaQAzG2Ceap5CWs9fokFFaSRqEeR7zXO9HPesLPQz/bmCpcpi6mQBQZx8yeHc48/UVXCczknwweUEtrUeceKxxHXeNhL2RjCV+/OPSmyXH6pM4oHroqjwhOqgeajB1aQ9r4Y9ZfvODNEa1zpqnkIIWZ9ypfXiBLBsdI+IINsb5ZJFXPvFKUI5ZvNQFHlTmDki11xBplUp5UUFzVmQfsStfvq9NafoXvozvtohahjLXWraMRXG2tE5YZt5xiVLm+srHaZM5fguCnQoET4d5Fny/kSzU0E0gFxpgF3ymb9U+DlyGMcOlIfjhQ7WtV4GCC9VdsiuoO2JTk2BzHdkuwhxmPktvCDBJcjABPe0MmjsUfaji5IXB6en5eGD2kbzOpktbjoCvZ8ZyD8093+1EqLWJIGZNWvxqBBHK5/5TIWTWAo/WHPawxQsDxwkLqFy9Z/yNTRqYgcekRdwWOQ9NvddTMvXto3uuPTYTC6xT9Di5A1MPecGh6zVZbWWCP/Sgyi8YIZgQbqgmu0WVNULx20C6jkir2xqqDaA6ACFqUt/GssrJDPS48lihyjXgY6qCLH7Dh0Yy7nMr1g+boVB7IH4Mhuz7kySxHE82FuhoOssaayRpSNHO7MPJaRjge4ZJA4CVYvT6hveZxTSs=
