language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "beatenpath";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: beaten-path
  api_key:
    secure: GaTuTUFN9pSfDayGf0ObcH5Dax/NclWLCHDW9qVB6F/idQWIvjU+gU33qmfrH6oF+w6EpGbbiqEuEP5ZWc56KjPz+7x3fqTs8H+9XTvRuD0nSL73cBiFKCBnbhtt6TfMYLfKhu785Vhy6yGDCPI9cTTjxkT7Ajz4B2I9R8P7vNxph2thAzOjXzrIf2DRC12kfUj6RiaeCFyw+/epYj6IuFOMtd+9uGAwKAL+TLZ4grGx6Mir5zG+nNb5+JozNk4j1tW6rZUFWhlRgAjm/nPuXfz2baT4CCxR1JBDLnzKxTgL2M1As0FfsERZuUDo1Mb95MVcfFgOhlA8wHm6g8KlBfTlKmnDM5gzebZM7Ow4xatxwU36AX1xobMFmjbfjJbuC4Rsm6moQnvGBg3ZovsNtfISJVnlWD3C6Neh6I6Qh80KefW8Dl8ckkAGpMd/FlReA/8R2znaXJZ1c2ZwMy+RfTVe9tvV39Bg5mL1mMkH75ltwdCGkxHABKHMj9jSvlHs4Otd1Sq0P3qtCoYOd6tSIKUir4h4zxsB+V5GT69qe9NSXT+IQfSBbEVympDkFAEJ8hbe2kR0CzyvIp7P+eK+T61gb7lIWS4KC/SYk8ScyhyB18DU2WJv9vf9GM+BWYFa/IWFC2fLyxIurFm5vf17RX9gCN0bb0BODNgJdRmO068=
