language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "beatenpath";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: beaten-path
  api_key:
    secure: POsuUnyo+f25kBuaw81jeH1KDaxWzAeM81tGA4rL87R9EJFgrVm45UPQuXcTeUXrs7S62eZRnfMAR3xJtDAcQYReyLARi6i5mQimVC1u9v8DhkLAswTuQm/rbIIlfaD3PugYJ+1yycJEjV9ShSKzm6rgPDP+S+lNI+R6SJfSNYCWvRztvlu2cqG/nqyAiVZrx7Z5uQ2iDOL7IHAOtJQQW3x9Wtg21pk1tUoq1s0+7HCnK1yNIfolxn5NK+9yPvHDETljOQtn3bP2MBIvvzX1yr9aOX7iax0qSbbOyWQvoSu+tDsvbIEwPvrVcQY96VGlDBfmqywAWZWc/YGbnDlZ9Pd/sTlVXqA5U7p4RIS2lsOnmGxmcXOGcHWReSPz9auv+Y1+0dNURfLoFd1+QSP0QxXY9Ed2RVa8nScaRgC2o42RclDET1akC4U4i8g1lRw8UPfcqmDX91kq2Aoka8TKTjk30ZC7cNMnvDEmxVqu8v+uLGs4fKtKxeHoMowTEPOIVgozHr9bgr9aO2qvshvb4n+V3S8mCQUd89szi1WMXzqRFHBxP3lbDKCKIXVbDzpgCMlTrzpZg9kPgTXlISnO5Jnon8nr8xLHyEN8r9hwBG/dC90PpIhIMsbdF/oERFjRzrFD6q+mUipHuDDGg7DlmSuDW7Q16+rblhi1kqZ1xVw=
